import uuid
from sqlalchemy import Column, String, Boolean, DateTime, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.models import Base

class User(Base):
    __tablename__ = "users"

    # Primary key — UUID generated by PostgreSQL
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    # Identity fields
    email = Column(String(255), unique=True, nullable=True)
    hashed_password = Column(String(255), nullable=True)
    full_name = Column(String(255), nullable=False)

    # Role — who is this user?
    role = Column(String(50), nullable=False, default="participant")

    # Status flags
    is_active = Column(Boolean, default=True, nullable=False)
    is_guest = Column(Boolean, default=False, nullable=False)

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc)
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    # Relationships — SQLAlchemy knows this user owns many quizzes
    quizzes = relationship("Quiz", back_populates="creator")
    hosted_sessions = relationship("QuizSession", back_populates="host")

    def __repr__(self):
        return f"<User {self.email} ({self.role})>"